import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../app/layout/Header/index";
import Footer from "./layout/Footer";
import AOS from "./src/components/AOS";
import 'swiper/css';
import 'swiper/css/pagination';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MettleSol",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AOS />
      <body>
        <Header />
        <main className="container max-w-full min-h-full box-border">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
